version: '3.7'
services:
  worker:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    command: bash worker.sh
    environment:
      ENABLE_SENTRY: 'yes'
      DATABASE_URL: 'postgresql://salem:AuroraAdminPanel321@postgres:5432/aurora'
      TRAFFIC_INTERVAL_SECONDS: 600
      DDNS_INTERVAL_SECONDS: 120
    volumes:
      - /.ssh/id_rsa:/app/ansible/env/ssh_key
      - /root/aurora/app-data:/app/ansible/priv_data_dirs
    depends_on:
      - redis

  backend:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic upgrade heads && python app/main.py"
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://salem:AuroraAdminPanel321@postgres:5432/aurora'
      ENABLE_SENTRY: 'yes'
      SECREY_KEY: 'AuroraAdminPanel321'
    volumes:
      - /root/aurora/app-data:/app/ansible/priv_data_dirs
    depends_on:
      - postgres
      - redis

  nginx:
    image: leishi1313/aurora-admin-frontend:latest
    restart: always
    ports:
      - 621:80
    depends_on:
      - backend
  
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: salem
      POSTGRES_PASSWORD: AuroraAdminPanel321
      POSTGRES_DB: aurora
    volumes:
      - /root/aurora/db-data:/var/lib/postgresql/data
      
  
volumes:
  db-data:
  app-data:
